### PR TITLE
Autogenerate room names based on names text files

### PR DESCRIPTION
**Pull request by idlechild**

### CODE REVIEW

**Comment by InsaneFirebat** [comment]
I don't really understand this. If the names only need to be created once, why would we want this as part of the build process?

**Comment by idlechild** [comment]
Just to make it easy to change names.  There's also the option to provide your own custom_names.txt to override specific room names.

That said, committing the generated file and just having the python script around to recreate it when needed also works.

**Comment by InsaneFirebat** [comment]
Would you mind if we eliminate the generated folder as well as commit roomnames.asm to src? I have the commit ready.

**Comment by idlechild** [comment]
I missed your comment.  Yes go ahead and do that.

**Comment by InsaneFirebat** [comment]
I did something differently in the GitHub app and it won't let me commit it to the pull now. Just gonna merge it make my commit to the branch after.

Edit:  I now see that the commit did go through, but it shows above your comment since it was created days earlier =/

**Pull request merged**
